APC.Manager.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APC.Manager.Web.Controllers {
	public class HomeController : Controller {
		public ActionResult Index() {
			ViewBag.Title = "Dashboard";
			ViewBag.ActiveTab = "Dashboard";

			return View();
		}
	}
}

APC.Manager.Web/Controllers/ThemeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APC.Manager.Web.Controllers {
	public class ThemeController : Controller {

		//
		// Example Pages
		//

		public ActionResult PageProfile() {
			ViewBag.Title = "Profile";
			ViewBag.ActiveTab = "Example Pages";

			return View();
		}

		public ActionResult PageInvoice() {
			ViewBag.Title = "Invoice";
			ViewBag.ActiveTab = "Example Pages";

			return View();
		}

		public ActionResult PagePricing() {
			ViewBag.Title = "Pricing Plans";
			ViewBag.ActiveTab = "Example Pages";

			return View();
		}

		public ActionResult PageSupport() {
			ViewBag.Title = "Support Page";
			ViewBag.ActiveTab = "Example Pages";

			return View();
		}

		public ActionResult PageGallery() {
			ViewBag.Title = "Gallery";
			ViewBag.ActiveTab = "Example Pages";

			return View();
		}

		public ActionResult PageSettings() {
			ViewBag.Title = "Settings";
			ViewBag.ActiveTab = "Example Pages";

			return View();
		}

		public ActionResult PageCalendar() {
			ViewBag.Title = "Calendar";
			ViewBag.ActiveTab = "Example Pages";

			return View();
		}


		//
		// Form Elements
		//

		public ActionResult FormRegular() {
			ViewBag.Title = "Regular Elements";
			ViewBag.ActiveTab = "Form Elements";

			return View();
		}

		public ActionResult FormExtended() {
			ViewBag.Title = "Extended Elements";
			ViewBag.ActiveTab = "Form Elements";

			return View();
		}

		public ActionResult FormValidation() {
			ViewBag.Title = "Validation";
			ViewBag.ActiveTab = "Form Elements";

			return View();
		}


		//
		// UI Features
		//

		public ActionResult UIButtons() {
			ViewBag.Title = "Buttons";
			ViewBag.ActiveTab = "UI Features";

			return View();
		}

		public ActionResult UITabs() {
			ViewBag.Title = "Tabs";
			ViewBag.ActiveTab = "UI Features";

			return View();
		}

		public ActionResult UIPopups() {
			ViewBag.Title = "Popups";
			ViewBag.ActiveTab = "UI Features";

			return View();
		}

		public ActionResult UISliders() {
			ViewBag.Title = "Sliders";
			ViewBag.ActiveTab = "UI Features";

			return View();
		}

		public ActionResult UITypography() {
			ViewBag.Title = "Typography";
			ViewBag.ActiveTab = "UI Features";

			return View();
		}

		public ActionResult UIIcons() {
			ViewBag.Title = "Icons";
			ViewBag.ActiveTab = "UI Features";

			return View();
		}


		//
		// Tables
		//

		public ActionResult TableBasic() {
			ViewBag.Title = "Basic Tables";
			ViewBag.ActiveTab = "Tables";

			return View();
		}

		public ActionResult TableAdvanced() {
			ViewBag.Title = "Advanced Tables";
			ViewBag.ActiveTab = "Tables";

			return View();
		}

		public ActionResult TableResponsive() {
			ViewBag.Title = "Responsive Tables";
			ViewBag.ActiveTab = "Tables";

			return View();
		}


		//
		// Portlets
		//

		public ActionResult UIPortlets() {
			ViewBag.Title = "Portlets";
			ViewBag.ActiveTab = "Portlets";

			return View();
		}

		//
		// Charts & Graphs
		//

		public ActionResult ChartFlot() {
			ViewBag.Title = "jQuery Flot";
			ViewBag.ActiveTab = "Charts & Graphs";

			return View();
		}

		public ActionResult ChartMorris() {
			ViewBag.Title = "Morris.js";
			ViewBag.ActiveTab = "Charts & Graphs";

			return View();
		}


		//
		// Extra Pages
		//

		public ActionResult PageLoginBasic() {
			ViewBag.Title = "Login - Basic";
			ViewBag.ActiveTab = "Extra Pages";

			return View();
		}

		public ActionResult PageLoginSocial() {
			ViewBag.Title = "Login - Social";
			ViewBag.ActiveTab = "Extra Pages";

			return View();
		}

		public ActionResult Page404() {
			ViewBag.Title = "Page Not Found";
			ViewBag.ActiveTab = "Extra Pages";

			return View();
		}

		public ActionResult Page500() {
			ViewBag.Title = "Internal Server Error";
			ViewBag.ActiveTab = "Extra Pages";

			return View();
		}

		public ActionResult PageBlank() {
			ViewBag.Title = "Blank Page";
			ViewBag.ActiveTab = "Extra Pages";

			return View();
		}
	}
}

APC.Manager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
	<title>@ViewBag.Title</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="">
	<meta name="author" content="" />

	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,800italic,400,600,800" type="text/css">

	<link rel="stylesheet" href="~/Theme/css/font-awesome.min.css" type="text/css" />
	<link rel="stylesheet" href="~/Theme/css/bootstrap.min.css" type="text/css" />
	<link rel="stylesheet" href="~/Theme/js/libs/css/ui-lightness/jquery-ui-1.9.2.custom.css" type="text/css" />
	
	@RenderSection("Styles", false)

	<link rel="stylesheet" href="~/Theme/css/App.css" type="text/css" />
	<link rel="stylesheet" href="~/Theme/css/custom.css" type="text/css" />
</head>

<body>

	<div id="wrapper">
		<header id="header">
			<h1 id="site-logo">
				<a href="@Url.Action("Index", "Home")">
					<img src="~/Theme/img/logos/logo.png" alt="Site Logo" />
				</a>
			</h1>

			<a href="javascript:;" data-toggle="collapse" data-target=".top-bar-collapse" id="top-bar-toggle" class="navbar-toggle collapsed">
				<i class="fa fa-cog"></i>
			</a>

			<a href="javascript:;" data-toggle="collapse" data-target=".sidebar-collapse" id="sidebar-toggle" class="navbar-toggle collapsed">
				<i class="fa fa-reorder"></i>
			</a>
		</header> <!-- header -->


		<nav id="top-bar" class="collapse top-bar-collapse">

			<ul class="nav navbar-nav pull-left">
				<li class="">
					<a href="@Url.Action("Index", "Home")">
						<i class="fa fa-home"></i>
						Home
					</a>
				</li>

				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;">
						Dropdown <span class="caret"></span>
					</a>

					<ul class="dropdown-menu" role="menu">
						<li><a href="javascript:;"><i class="fa fa-user"></i>&nbsp;&nbsp;Example #1</a></li>
						<li><a href="javascript:;"><i class="fa fa-calendar"></i>&nbsp;&nbsp;Example #2</a></li>
						<li class="divider"></li>
						<li><a href="javascript:;"><i class="fa fa-tasks"></i>&nbsp;&nbsp;Example #3</a></li>
					</ul>
				</li>

			</ul>

			<ul class="nav navbar-nav pull-right">
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;">
						<i class="fa fa-user"></i>
						Elizabeth Legere
						<span class="caret"></span>
					</a>

					<ul class="dropdown-menu" role="menu">
						<li>
							<a href="@Url.Action("PageProfile", "Theme")">
								<i class="fa fa-user"></i>
								&nbsp;&nbsp;My Profile
							</a>
						</li>
						<li>
							<a href="@Url.Action("PageCalendar", "Theme")">
								<i class="fa fa-calendar"></i>
								&nbsp;&nbsp;My Calendar
							</a>
						</li>
						<li>
							<a href="@Url.Action("PageSettings", "Theme")">
								<i class="fa fa-cogs"></i>
								&nbsp;&nbsp;Settings
							</a>
						</li>
						<li class="divider"></li>
						<li>
							<a href="@Url.Action("PageLogin", "Theme")">
								<i class="fa fa-sign-out"></i>
								&nbsp;&nbsp;Logout
							</a>
						</li>
					</ul>
				</li>
			</ul>

		</nav> <!-- /#top-bar -->


		<div id="sidebar-wrapper" class="collapse sidebar-collapse">

			<div id="search">
				<form>
					<input class="form-control input-sm" type="text" name="search" placeholder="Search..." />

					<button type="submit" id="search-btn" class="btn"><i class="fa fa-search"></i></button>
				</form>
			</div> <!-- #search -->

			<nav id="sidebar">

				<ul id="main-nav" class="open-active">

					@if (ViewBag.ActiveTab == "Dashboard") {
						<text>
							<li class="active">
						</text>
					}
					else {
						<text>
							<li>
						</text>
					}
						<a href="@Url.Action("Index", "Home")">
							<i class="fa fa-dashboard"></i>
							Dashboard
						</a>
					</li>

					@if (ViewBag.ActiveTab == "Example Pages") {
						<text>
							<li class="dropdown active" >
						</text>
					}
					else {
						<text>
							<li class="dropdown">
						</text>
					}
						<a href="javascript:;">
							<i class="fa fa-file-text"></i>
							Example Pages
							<span class="caret"></span>
						</a>

						<ul class="sub-nav">
							<li>
								<a href="@Url.Action("PageProfile", "Theme")">
									<i class="fa fa-user"></i>
									Profile
								</a>
							</li>
							<li>
								<a href="@Url.Action("PageInvoice", "Theme")">
									<i class="fa fa-money"></i>
									Invoice
								</a>
							</li>
							<li>
								<a href="@Url.Action("PagePricing", "Theme")">
									<i class="fa fa-dollar"></i>
									Pricing Plans
								</a>
							</li>
							<li>
								<a href="@Url.Action("PageSupport", "Theme")">
									<i class="fa fa-question"></i>
									Support Page
								</a>
							</li>
							<li>
								<a href="@Url.Action("PageGallery", "Theme")">
									<i class="fa fa-picture-o"></i>
									Gallery
								</a>
							</li>
							<li>
								<a href="@Url.Action("PageSettings", "Theme")">
									<i class="fa fa-cogs"></i>
									Settings
								</a>
							</li>
							<li>
								<a href="@Url.Action("PageCalendar", "Theme")">
									<i class="fa fa-calendar"></i>
									Calendar
								</a>
							</li>
						</ul>

					</li>

					@if (ViewBag.ActiveTab == "Form Elements") {
						<text>
							<li class="dropdown active">
						</text>
					}
					else {
						<text>
							<li class="dropdown">
						</text>
					}
						<a href="javascript:;">
							<i class="fa fa-tasks"></i>
							Form Elements
							<span class="caret"></span>
						</a>

						<ul class="sub-nav">
							<li>
								<a href="@Url.Action("FormRegular", "Theme")">
									<i class="fa fa-location-arrow"></i>
									Regular Elements
								</a>
							</li>
							<li>
								<a href="@Url.Action("FormExtended", "Theme")">
									<i class="fa fa-magic"></i>
									Extended Elements
								</a>
							</li>
							<li>
								<a href="@Url.Action("FormValidation", "Theme")">
									<i class="fa fa-check"></i>
									Validation
								</a>
							</li>
						</ul>

					</li>

					@if (ViewBag.ActiveTab == "UI Features") {
						<text>
							<li class="dropdown active">
						</text>
					}
					else {
						<text>
							<li class="dropdown">
						</text>
					}
						<a href="javascript:;">
							<i class="fa fa-desktop"></i>
							UI Features
							<span class="caret"></span>
						</a>

						<ul class="sub-nav">
							<li>
								<a href="@Url.Action("UIButtons", "Theme")">
									<i class="fa fa-hand-o-up"></i>
									Buttons
								</a>
							</li>
							<li>
								<a href="@Url.Action("UITabs", "Theme")">
									<i class="fa fa-reorder"></i>
									Tabs & Accordions
								</a>
							</li>

							<li>
								<a href="@Url.Action("UIPopups", "Theme")">
									<i class="fa fa-asterisk"></i>
									Popups / Notifications
								</a>
							</li>

							<li>
								<a href="@Url.Action("UISliders", "Theme")">
									<i class="fa fa-tasks"></i>
									Sliders
								</a>
							</li>

							<li class="">
								<a href="@Url.Action("UITypography", "Theme")">
									<i class="fa fa-font"></i>
									Typography
								</a>
							</li>

							<li class="">
								<a href="@Url.Action("UIIcons", "Theme")">
									<i class="fa fa-star-o"></i>
									Icons
								</a>
							</li>
						</ul>
					</li>

					@if (ViewBag.ActiveTab == "Tables") {
						<text>
							<li class="dropdown active">
						</text>
					}
					else {
						<text>
							<li class="dropdown">
						</text>
					}
						<a href="javascript:;">
							<i class="fa fa-table"></i>
							Tables
							<span class="caret"></span>
						</a>

						<ul class="sub-nav">
							<li>
								<a href="@Url.Action("TableBasic", "Theme")">
									<i class="fa fa-table"></i>
									Basic Tables
								</a>
							</li>
							<li>
								<a href="@Url.Action("TableAdvanced", "Theme")">
									<i class="fa fa-table"></i>
									Advanced Tables
								</a>
							</li>
							<li>
								<a href="@Url.Action("TableResponsive", "Theme")">
									<i class="fa fa-table"></i>
									Responsive Tables
								</a>
							</li>
						</ul>

					</li>

					@if (ViewBag.ActiveTab == "Portlets") {
						<text>
							<li class="active">
						</text>
					}
					else {
						<text>
							<li>
						</text>
					}
						<a href="@Url.Action("UIPortlets", "Theme")">
							<i class="fa fa-list-alt"></i>
							Portlets
						</a>
					</li>

					@if (ViewBag.ActiveTab == "Charts & Graphs") {
						<text>
							<li class="dropdown active">
						</text>
					}
					else {
						<text>
							<li class="dropdown">
						</text>
					}
						<a href="javascript:;">
							<i class="fa fa-bar-chart-o"></i>
							Charts & Graphs
							<span class="caret"></span>
						</a>

						<ul class="sub-nav">
							<li>
								<a href="@Url.Action("ChartFlot", "Theme")">
									<i class="fa fa-bar-chart-o"></i>
									jQuery Flot
								</a>
							</li>
							<li>
								<a href="@Url.Action("ChartMorris", "Theme")">
									<i class="fa fa-bar-chart-o"></i>
									Morris.js
								</a>
							</li>
						</ul>
					</li>

					@if (ViewBag.ActiveTab == "Extra Pages") {
						<text>
							<li class="dropdown active">
						</text>
					}
					else {
						<text>
							<li class="dropdown">
						</text>
					}
						<a href="javascript:;">
							<i class="fa fa-file-text-o"></i>
							Extra Pages
							<span class="caret"></span>
						</a>

						<ul class="sub-nav">
							<li>
								<a href="@Url.Action("PageLoginBasic", "Theme")">
									<i class="fa fa-unlock"></i>
									Login Basic
								</a>
							</li>
							<li>
								<a href="@Url.Action("PageLoginSocial", "Theme")">
									<i class="fa fa-unlock"></i>
									Login Social
								</a>
							</li>
							<li>
								<a href="@Url.Action("Page404", "Theme")">
									<i class="fa fa-ban"></i>
									404 Error
								</a>
							</li>
							<li>
								<a href="@Url.Action("Page500", "Theme")">
									<i class="fa fa-ban"></i>
									500 Error
								</a>
							</li>
							<li>
								<a href="@Url.Action("PageBlank", "Theme")">
									<i class="fa fa-file-text-o"></i>
									Blank Page
								</a>
							</li>
						</ul>
					</li>

				</ul>

			</nav> <!-- #sidebar -->

		</div> <!-- /#sidebar-wrapper -->


		<div id="content">
			<div id="content-header">
				<h1>@ViewBag.Title</h1>
			</div> <!-- #content-header -->

			<div id="content-container">

				@RenderBody()

			</div> <!-- /#content-container -->
		</div> <!-- #content -->
	</div> <!-- #wrapper -->

	<footer id="footer">
		<ul class="nav pull-right">
			<li>
				Copyright &copy; @DateTime.Now.Year, Alexandria Pet Care, Inc.
			</li>
		</ul>
	</footer>

	@RenderSection("ModalPopups", false)

	<script src="~/Theme/js/libs/jquery-1.9.1.min.js"></script>
	<script src="~/Theme/js/libs/jquery-ui-1.9.2.custom.min.js"></script>
	<script src="~/Theme/js/libs/bootstrap.min.js"></script>

	@RenderSection("Scripts", false)

	<script src="~/Theme/js/App.js"></script>
</body>
</html>

APC.Manager.Web/Views/Theme/FormValidation.cshtml
<div class="row">

	<div class="col-sm-6">

		<div class="portlet">

			<div class="portlet-header">

				<h3>
					<i class="fa fa-tasks"></i>
					Enhanced Fields
				</h3>

			</div> <!-- /.portlet-header -->

			<div class="portlet-content">

				<form id="validate-enhanced" action="@Url.Action("FormValidation", "Theme")" class="form parsley-form">

					<div class="form-group">
						<label for="validateSelect">Select2 Field</label>
						<select name="select-2" class="form-control select2-input" data-required="true">
							<option value="">Please Select</option>
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
							<option value="4">4</option>
							<option value="5">5</option>
							<option value="6">6</option>
						</select>
					</div>
					<div class="form-group">
						<label for="select-multi-input">Select2 Multiple Field</label>
						<select name="select-multi-2" multiple class="form-control select2-input" data-required="true">
							<option>1</option>
							<option>2</option>
							<option>3</option>
							<option>4</option>
							<option>5</option>
							<option>6</option>
						</select>
					</div>

					<div class="form-group">
						<label for="date-2">Date Picker</label>

						<div class="input-group date ui-datepicker">
							<input id="date-2" name="date-2" class="form-control" type="text" data-required="true">
							<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
						</div>
					</div>

					<div class="form-group">
						<label for="time-2">Time Picker</label>

						<div class="input-group bootstrap-timepicker">
							<input id="time-2" name="time-2" class="form-control ui-timepicker" data-value="" type="text" data-required="true">
							<span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
						</div>
					</div>

					<div class="form-group">
						<label for="color-2">Color Picker</label>
						<select id="color-2" name="colorpicker" class="form-control ui-colorpicker" data-required="true">
							<!-- Colors from Google Calendar -->
							<option value="">Select</option>
							<option value="#e5412d">Red</option>
							<option value="#f0ad4e">Yellow</option>
							<option value="#428bca">Blue</option>
							<option value="#5cb85c">Green</option>
							<option value="#5bc0de">Teal</option>
						</select>
					</div>

					<div class="form-group">
						<label>iCheck Checkbox Field</label>
						<div class="checkbox">
							<label>
								<input type="checkbox" name="checkbox-2" class="icheck-input" data-mincheck="2">
								Option 1
							</label>
						</div>
						<div class="checkbox">
							<label>
								<input type="checkbox" name="checkbox-2" class="icheck-input" data-mincheck="2">
								Option 2
							</label>
						</div>
					</div> <!-- /.form-group -->


					<div class="form-group">
						<label>iCheck Radio Field</label>
						<div class="radio">
							<label>
								<input type="radio" name="radio-2" class="icheck-input" data-required="true">
								Option 1
							</label>
						</div>
						<div class="radio">
							<label>
								<input type="radio" name="radio-2" class="icheck-input" data-required="true">
								Option 2
							</label>
						</div>
					</div> <!-- /.form-group -->



					<div class="form-group">
						<button type="submit" class="btn btn-primary">Validate</button>
					</div>

				</form>

			</div> <!-- /.portlet-content -->

		</div> <!-- /.portlet -->

	</div> <!-- /.col -->







	<div class="col-sm-6">

		<div class="portlet">

			<div class="portlet-header">

				<h3>
					<i class="fa fa-tasks"></i>
					Basic Fields
				</h3>

			</div> <!-- /.portlet-header -->

			<div class="portlet-content">

				<form id="validate-basic" action="@Url.Action("FormValidation", "Theme")" data-validate="parsley" class="form parsley-form">

					<div class="form-group">
						<label for="name">Name</label>
						<input type="text" id="name" name="name" class="form-control" data-required="true">
					</div>

					<div class="form-group">
						<label for="textarea-input">Textarea</label>
						<textarea data-required="true" data-minlength="5" name="textarea-input" id="textarea-input" cols="10" rows="2" class="form-control"></textarea>
					</div>

					<div class="form-group">
						<label for="validateSelect">Select</label>
						<select id="validateSelect" name="validateSelect" class="form-control" data-required="true">
							<option value="">Please Select</option>
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
							<option value="4">4</option>
							<option value="5">5</option>
							<option value="6">6</option>
						</select>
					</div>
					<div class="form-group">
						<label for="select-multi-input">Select (multiple)</label>
						<select data-required="true" multiple id="select-multi-input" class="form-control">
							<option>1</option>
							<option>2</option>
							<option>3</option>
							<option>4</option>
							<option>5</option>
							<option>6</option>
						</select>
					</div>

					<div class="form-group">
						<label>Checkbox (stacked)</label>
						<div class="checkbox">
							<label>
								<input type="checkbox" name="checkbox-1" class="" data-mincheck="2">
								Option 1
							</label>
						</div>
						<div class="checkbox">
							<label>
								<input type="checkbox" name="checkbox-1" class="" data-mincheck="2">
								Option 2
							</label>
						</div>
					</div> <!-- /.form-group -->


					<div class="form-group">
						<label>Radio (stacked)</label>
						<div class="radio">
							<label>
								<input type="radio" name="radio-1" class="" data-required="true">
								Option 1
							</label>
						</div>
						<div class="radio">
							<label>
								<input type="radio" name="radio-1" class="" data-required="true">
								Option 2
							</label>
						</div>
					</div> <!-- /.form-group -->

					<div class="form-group">
						<button type="submit" class="btn btn-primary">Validate</button>
					</div>

				</form>

			</div> <!-- /.portlet-content -->

		</div> <!-- /.portlet -->

	</div> <!-- /.col -->

</div> <!-- /.row -->

@section Styles {
	<link rel="stylesheet" href="~/Theme/js/plugins/icheck/skins/minimal/blue.css" type="text/css" />
	<link rel="stylesheet" href="~/Theme/js/plugins/datepicker/datepicker.css" type="text/css" />
	<link rel="stylesheet" href="~/Theme/js/plugins/select2/select2.css" type="text/css" />
	<link rel="stylesheet" href="~/Theme/js/plugins/simplecolorpicker/jquery.simplecolorpicker.css" type="text/css" />
	<link rel="stylesheet" href="~/Theme/js/plugins/timepicker/bootstrap-timepicker.css" type="text/css" />
	<link rel="stylesheet" href="~/Theme/js/plugins/fileupload/bootstrap-fileupload.css" type="text/css" />
}

@section Scripts {
	<script src="~/Theme/js/plugins/parsley/parsley.js"></script>

	<script src="~/Theme/js/plugins/icheck/jquery.icheck.js"></script>
	<script src="~/Theme/js/plugins/datepicker/bootstrap-datepicker.js"></script>
	<script src="~/Theme/js/plugins/timepicker/bootstrap-timepicker.js"></script>
	<script src="~/Theme/js/plugins/simplecolorpicker/jquery.simplecolorpicker.js"></script>
	<script src="~/Theme/js/plugins/select2/select2.js"></script>

	<script>
		$(function () {
			$('.select2-input').select2({
				placeholder: "Select..."
			});

			// Just for the demo
			$('#time-2').val('');
		});
	</script>
}

APC.Manager.Web/Views/Theme/PageCalendar.cshtml
<div class="row">

	<div class="col-md-8">

		<div class="portlet">

			<div class="portlet-header">

				<h3>
					<i class="fa fa-calendar"></i>
					Full Calendar
				</h3>

			</div> <!-- /.portlet-header -->

			<div class="portlet-content">

				<div id="full-calendar"></div> <!-- /#full-calendar -->

			</div> <!-- /.portlet-content -->

		</div> <!-- /.portlet -->

	</div> <!-- /.col-md-8 -->



	<div class="col-md-4">

		<div class="well">

			<div id="external-events">
				<h4>Add an Event</h4>

				<form id="event-form" class="form">
					<div class="form-group">
						<input type="text" value="" class="form-control" placeholder="Event Title..." id="event_title" />
					</div> <!-- /.form-group -->

					<div class="form-group">
						<select id="event_category" name="event_category" class="form-control">
							<option value="fc-red">Red Event</option>
							<option value="fc-yellow">Yellow Event</option>
							<option value="fc-grey">Grey Event</option>
							<option value="fc-charcoal">Charcoal Event</option>
						</select>
					</div> <!-- /.form-group -->

					<div class="form-group">
						<button type="submit" id="event_add" class="btn btn-tertiary btn-sm">Add Event</button>
					</div> <!-- /.form-group -->
				</form>

				<hr />

				<h4>Draggable Events</h4>


				<div id="event_box">
					<div class="external-event label ui-draggable fc-red" data-category="fc-red">My Event 1</div>
					<div class="external-event label ui-draggable fc-yellow" data-category="fc-yellow">My Event 2</div>
					<div class="external-event label ui-draggable fc-grey" data-category="fc-grey">My Event 3</div>
					<div class="external-event label ui-draggable fc-charcoal" data-category="fc-charcoal">My Event 4</div>
				</div>
			</div>

		</div> <!-- /.well -->

	</div> <!-- /.col-md-4 -->


</div> <!-- /.row -->

@section Styles {
	<link rel="stylesheet" href="~/Theme/js/plugins/fullcalendar/fullcalendar.css" type="text/css" />
}

@section Scripts {
	<script src="~/Theme/js/plugins/fullcalendar/fullcalendar.min.js"></script>
	<script src="~/Theme/js/demos/calendar.js"></script>
}